name: test-minimalist
on: [pull_request]

jobs:
  test:
    name: test-minimalist
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.5
      - uses: actions/setup-node@v2.5.1
        with:
          node-version: "16"
      - name: Install dependencies
        run: |
          npm i
      - name: Lint Minimalist
        run: |
          npm lint
